basePath: /api/v1
info:
  contact: {}
paths:
  /emp:
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
  /emp/:id:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
  /emp/vacs/id:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
  /vac:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
    post:
      responses:
        "200":
          description: OK
          schema:
            type: string
  /vac/:id:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
swagger: "2.0"
