env: "local" # но может быть local, dev, prod. Этот параметр показывает на какой машине работает наша программа. В нашем случае на local
storage_path: "storage/storage.db" # Показывает, где хранится файл базы данных
http_server:
    address: "0.0.0.0:4252"
    timeout: 10s
    idle_timeout: 60s